require "json"

file = File.read(File.expand_path("~/.lua/packer-variables.json"))
data = JSON.parse(file)


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id     = data["aws_access_key"]
    aws.secret_access_key = data["aws_secret_key"]
    aws.keypair_name      = "lua-default"
    aws.instance_type     = "m3.medium"
    aws.security_groups   = [
      "default",
      "app_server",
      "can-access-rds-staging",
      "can-access-redis-staging",
    ]

    # SPECIFY AMI HERE
    aws.ami = ""

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/lua-default.pem"
  end
end
