---
# Elasticsearch Ansible Variables

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch
elasticsearch_version: 1.4.0
elasticsearch_apt_repos:
  - 'ppa:webupd8team/java'
elasticsearch_apt_java_package: oracle-java7-installer
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
elasticsearch_max_open_files: 65535
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /mnt
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /usr/share/elasticsearch/config
elasticsearch_pidfile: "/var/run/elasticsearch.pid"
elasticsearch_logfile: "/var/log/elasticsearch-output.log"
elasticsearch_heap_size: 2g
elasticsearch_max_locked_memory: unlimited
elasticsearch_timezone: "America/New_York"
elasticsearch_node_max_local_storage_nodes: 1
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_misc_auto_create_index: "true"
elasticsearch_misc_query_bool_max_clause_count: 4096
elasticsearch_misc_disable_delete_all_indices: "true"
elasticsearch_java_opts: "-XX:-UseSuperWord"

# Non-Elasticsearch Defaults
apt_cache_valid_time: 300 # seconds between "apt-get update" calls.
elasticsearch_install_java: "true"
