- name: Install native gem building dependencies
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - libxslt1-dev
    - libxml2-dev
    - build-essential
    - libmagic-dev
    - libsqlite3-dev

- name: Install mysql ruby dependencies
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - libmysqlclient-dev
    - mysql-client

- name: Install all the gems from local gem cache
  command: /usr/local/bin/bundle install --local --path=vendor/bundle chdir={{ rails_root }}
  sudo_user: vagrant

- name: Install custom bashrc
  template: src=bashrc dest=/home/vagrant/.bashrc mode=644

- name: Create the log directory
  file: path={{ rails_root }}/log state=directory

- name: Update inotify limit (required for running guard)
  command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  sudo_user: vagrant